dbc_overflow/config/routes.rb
Rails.application.routes.draw do
  root to: 'application#index'

  get '/sessions/login', to: 'sessions#login', as: 'login'
  post '/sessions', to: 'sessions#validate_credentials'
  delete '/sessions', to: 'sessions#logout'

  get '/users/new', to: 'users#new'
  post '/users', to: 'users#create'
  
  get '/questions', to: 'questions#index'
  get '/questions/new', to: 'questions#new'
  post '/questions', to: 'questions#create'
  get '/questions/:id', to: 'questions#show', as: 'questions_show'

  get '/answers', to: 'answers#index'
  get '/answers/new', to: 'answers#new'
  post '/answers', to: 'answers#create'
end

dbc_overflow/app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :content, presence: true
  validates :score, numericality: true

  belongs_to :question
  belongs_to :user
  has_many :responses, as: :response_to
  has_many :votes, as: :vote_for

  def user
    User.find(self.user_id.to_i).username
  end
end

dbc_overflow/app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, :content, presence: true
  validates :score, numericality: true

  belongs_to :user
  has_many :answers
  has_many :votes, as: :vote_for
  has_many :responses, as: :response_to
end

dbc_overflow/app/models/response.rb
class Response < ActiveRecord::Base
  validates	:content, presence: true

  belongs_to :user
  belongs_to :response_to, :polymorphic => true
  has_many :votes, as: :vote_for

  def owner
    return response_to.title if response_to.is_a? Question
    return "An Answer" if response_to.class.is_a? Answer
  end
end

dbc_overflow/app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true
  # validates :email, uniquesness: true

  has_many :questions
  has_many :answers
  has_many :votes
  has_many :responses
end

dbc_overflow/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :vote_for, :polymorphic => true
end

dbc_overflow/app/controllers/answers_controller.rb
class AnswersController < ActionController::Base
  respond_to :html, :js

  def index
  end

  def new
    @answer = Answer.new
  end

  def create
    question = Question.find(params[:id])
    @answer = Answer.create(content: params[:content], score: 0, user_id: session[:user_id])
    question.answers << @answer
  end

  private

  def answer_params
    params.require(:answer).permit(:content)
  end
end

dbc_overflow/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    redirect_to login_path if session[:user_id].nil?
    @questions = Question.all
  end
end

dbc_overflow/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.create
  end

  def show
    @question = Question.find(params[:id])
    @user = User.find(@question.user_id)
    render :index
  end
end

dbc_overflow/app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def index
    response_to = find_response_to
    @responses = response_to.responses
  end
  private
  def find_response_to
    case params[:response_to_type]
    when "question"
      Question.find[:response_to_id]
    when "answer"
      Answer.find[:response_to_id]
  end
end

dbc_overflow/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def login
    if session[:user_id].nil?
      render :login
    else
      redirect_to root_path
    end
  end

  def validate_credentials
    user = User.find_by_email(params[:email])
    user_password = BCrypt::Password.new(user.password_hash)

    if user && user_password == params[:password]
      session[:user_id] = user.id
      redirect_to root_path
      puts "AUTHENTICATED!!!"
    else
      flash.now.alert = "Invalid email or password"
      render :login
      puts "NOT AUTHENTICATED!!!"
    end

    puts ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    p user.email
    p params[:password]
    p user && BCrypt::Password.new(user.password_hash) == params[:password]
    p user.password_hash
    p BCrypt::Password.new(user.password_hash)
    puts ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"

  end




  def logout
    session[:user_id] = nil
    redirect_to root_path
  end
end

dbc_overflow/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
    if session[:user_id].nil?
      render :login
    else
      redirect_to root_path
    end
  end

  def validate_credentials
    user = User.find_by_email(params[:email])
    user_password = BCrypt::Password.new(user.password_hash)

    if user && user_password == params[:password]
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now.alert = "Invalid email or password"
      render :login
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end
end

dbc_overflow/app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @user = User.new
  end

  def create
    password_hash = BCrypt::Password.create(params[:user][:password])
    @user = User.create(email: params[:user][:email], password_hash: password_hash )
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to root_path
    else
      :new
    end
  end

end

dbc_overflow/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    password_hash = BCrypt::Password.create(params[:user][:password])
    @user = User.create(email: params[:user][:email], password_hash: password_hash )
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to root_path
    else
      :new
    end
  end

end

dbc_overflow/app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def upvote
    vote_for = find_vote_for
    cast_vote(vote_for, 1)
    page_question = Question.find(vote_for.question.id)
    redirect_to question_path(page_question)
  end

  def downvote
    vote_for = find_vote_for
    cast_vote(vote_for, -1)
    page_question = Question.find(vote_for.question.id)
    redirect_to question_path(page_question)
  end

  private
  def cast_vote(v_for, v_value)
      v_for.votes.create(
        user_id: session[:user_id],
        vote_value: v_value,
      )
  end

  def find_vote_for
    case params[:vote_for_type]
    when "question"
      Question.find(params[:vote_for_id])
    when "answer"
      Answer.find(params[:vote_for_id])
    when "response"
      Response.find(params[:vote_for_id])
    end
  end
end

dbc_overflow/app/helpers/application_helper.rb
module ApplicationHelper
end

dbc_overflow/app/helpers/question_helper.rb
module QuestionHelper
end

dbc_overflow/app/helpers/questions_helper.rb
module QuestionsHelper
end

dbc_overflow/app/views/answers/_answer.html.erb
<li>
  <p><%= @answer.content %></p> 
</li>

dbc_overflow/app/views/answers/create.js.erb
$('.ul_answers').append("<%= j (render 'answer') %>");
$('#content').val("");
$('#answer-form').css("display", "none");

dbc_overflow/app/views/answers/new.js.erb
$("#answer-form").css("display", "block");

dbc_overflow/app/views/application/index.html.erb
<%= link_to "Logout", sessions_path, method: :delete %>

<div>
  <h1>Hello user! Welcome to Frankenstein Overflow!</h1>
</div>

<%  @questions.each do |question| %>
  <div>
    <h3><span><!-- Vote total Goes here --></span><%= link_to question.title, questions_show_path(question.id) %></h3>
    <p><%= question.content %></p>
  </div>
<% end %>

dbc_overflow/app/views/home/index.html.erb
<%= link_to "Logout", session_path, method: :delete %>

<div>
  <h1>Hello user! Welcome to Frankenstein Overflow!</h1>
</div>

<%  @questions.each do |question| %>
  <div>
    <h3><span><!-- Vote total Goes here --></span><%= link_to question.title, question_path(question) %></h3>
    <p><%= question.content %></p>
  </div>
<% end %>

dbc_overflow/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DbcOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

dbc_overflow/app/views/questions/index.html.erb
<div>
  <h2><%= @question.title %></h2>
  <h6><%= @question.score %></h6>
  <h6><%= @user.email %></h6>
  <p><%= @question.content %></p>
  <%= link_to answers_new_path, remote: true do %>
    <button>Add answer!</button>
  <% end %>
  <div id="answer-form" style="display:none;">
    <%= form_tag answers_path(:id => @question.id), remote: true do |f| %>
      <%= label_tag "Your Answer" %>
      <%= text_field_tag :content %>
      <%= submit_tag "Submit" %>
    <% end %>
  </div>
  <div>
    <% @question.responses.each do |comment| %>
      <h6>User A</h6>
      <p><%= comment.content %></p>
    <% end %>
  </div>
  <div>
    <ul class="ul_answers">
      <% @question.answers.each do |answer| %>
        <li>
          <p><%= answer.content %></p>
          <h6><%= answer.user %></h6>
          <h6><%= answer.score %></h6>
          <div>
            <% answer.responses.each do |comment| %>
              <p><%= comment.content %></p>
              <h6>User Y</h6>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

dbc_overflow/app/views/response/_response.html.erb
<div class="response-text">
  <h4><%= response.response_to.user.email %> sez:</h4>
  <p><%= response.content %></p>
</div>

dbc_overflow/app/views/response/index.html.erb
<h2>Responses to <%= @responses.first.owner %></h2>
<ul>
  <% @responses.each do |response| %>
    <li><%= render "response", locals: {response: response} %></li>
  <% end %>
</ul>

dbc_overflow/app/views/users/new.html.erb
<div>
  <%= form_for @user do |f| %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <%= f.submit "Sign Up" %>
  <% end %>
</div>